name: Build OS Packages

on:
  push:
    branches:
      - 'main'

jobs:
  build-macos:
    runs-on: ${{ matrix.build.runner }}
    strategy:
      fail-fast: false
      matrix:
        build:
          - runner: macos-13
          - runner: macos-14
    steps:
      - name: Set variables
        run: |
          echo "ANON_ARTIFACTS=anon-macos-$(uname -m)" >> $GITHUB_ENV
          echo "ANON_BREW_PREFIX=$(brew --prefix)" >> $GITHUB_ENV
      - name: Build
        run: |
          brew install automake docbook docbook-xsl zlib libevent openssl@3

          git clone https://github.com/ATOR-Development/ator-protocol.git
          cd ator-protocol

          ./autogen.sh
          ./configure --prefix=/usr/local \
            --disable-asciidoc \
            --disable-zstd \
            --disable-lzma \
            --with-zlib-dir=${{ env.ANON_BREW_PREFIX }}/opt/zlib \
            --with-libevent-dir=${{ env.ANON_BREW_PREFIX }}/opt/libevent \
            --with-openssl-dir=${{ env.ANON_BREW_PREFIX }}/opt/openssl@3 \
            --enable-static-zlib \
            --enable-static-libevent \
            --enable-static-openssl \
            --disable-tool-name-check \
            --disable-gcc-hardening
          make
      - name: Copy binaries
        run: |
          mkdir -p ${{ env.ANON_ARTIFACTS }}
          cp ator-protocol/src/app/anon ${{ env.ANON_ARTIFACTS }}
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.ANON_ARTIFACTS }}
          path: ${{ env.ANON_ARTIFACTS }}
