name: Build Docker Image

on:
  push:
    branches:
      - 'main'

jobs:
  build:
    runs-on: macos-14
    steps:
      - name: Set up Docker Buildx
        run: |
          brew install automake docbook docbook-xsl zlib libevent openssl@3

          git clone https://github.com/ATOR-Development/ator-protocol.git
          cd ator-protocol

          ./autogen.sh
          ./configure --prefix=/usr/local \
            --disable-asciidoc \
            --disable-zstd \
            --disable-lzma \
            --with-zlib-dir=/opt/homebrew/opt/zlib \
            --with-libevent-dir=/opt/homebrew/opt/libevent \
            --with-openssl-dir=/opt/homebrew/opt/openssl@3 \
            --enable-static-zlib \
            --enable-static-libevent \
            --enable-static-openssl \
            --disable-tool-name-check \
            --disable-gcc-hardening
          make
      - name: Copy binaries
        run: |
          mkdir -p macos-binaries/
          cp ator-protocol/src/app/anon macos-binaries/
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: macos-binaries
          path: macos-binaries/
