name: Build Docker Image

on:
  push:
    branches:
      - 'main'

jobs:
  build:
    runs-on: ${{ matrix.build.runner }}
    strategy:
      fail-fast: false
      matrix:
        build:
          - runner: macos-13
            libdir: /usr/local/opt
          - runner: macos-14
            libdir: /opt/homebrew/opt
    steps:
      - name: Build
        run: |
          brew install automake docbook docbook-xsl zlib libevent openssl@3

          git clone https://github.com/ATOR-Development/ator-protocol.git
          cd ator-protocol

          ./autogen.sh
          ./configure --prefix=/usr/local \
            --disable-asciidoc \
            --disable-zstd \
            --disable-lzma \
            --with-zlib-dir=${{ matrix.build.libdir }}/zlib \
            --with-libevent-dir=${{ matrix.build.libdir }}/libevent \
            --with-openssl-dir=${{ matrix.build.libdir }}/openssl@3 \
            --enable-static-zlib \
            --enable-static-libevent \
            --enable-static-openssl \
            --disable-tool-name-check \
            --disable-gcc-hardening
          make
      - name: Set variables
        run: |
          echo "ANON_ARCH=$(uname -m)" >> $GITHUB_ENV
      - name: Copy binaries
        run: |
          mkdir -p macos-binaries/
          cp ator-protocol/src/app/anon macos-${{ env.ANON_ARCH }}-binaries/
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: macos-${{ env.ANON_ARCH }}-binaries
          path: macos-${{ env.ANON_ARCH }}-binaries/
